### ISSUE TITLE
[Monster] (infra)-repository

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/WebRPG#1]
## Description
-Repository 를 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.

- ``findMonsterBySequence()`` (시퀀스로 몬스터를 찾는 메소드)
- ``getMonsterDefaultHpBySequence`` (시퀀스로 몬스터의 기본 체력을 찾는 메소드)
---

## TODO
- [x]  domain repository 구현
- [x]  mosterDB로 객체 생성
- [x]  주요 메소드 작성

---

## ETC

---
* 없음
