### ISSUE TITLE
[Upgrade] 강화 이후 소지금이 두배가 되는 문제가 있음

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/WebRPG#105]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.

---
실제 소지금은 줄어드는 것으로 보이나, 표시되는 소지금이 다름
강화 실제 소비 비용도 점검 필요
---

## TODO
- [x]  할일 목록을 작성한다.
- [x]  할일 목록을 작성한다.
- [x]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
