### ISSUE TITLE
[Html] 배경음악 및 효과음 설정

### ISSUE THREAD

**Issue by happy-baechuchu** [MetaAir2023/WebRPG#124]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.
- [x] Create
---

## 주요 메서드 로직

1. 오디오 태그

---

## 메서드
해당 클래스의 주요 메서드를 입력합니다.   

- ``audio``    

---

## TODO
- [x]  업그레이드 화면 배경음악
- [x]  업그레이드 결과 효과음
- [x]  속성 선택 화면 배경음악
- [x] 헌트맵 1~10 배경음악

---

## ETC

---
* 업그레이드 결과가 한 html 안에서 이루어 짐 -> 성공/실패에 따른 효과음 두 가지 설정 불가능
* 업그레이드 성공 실패 여부 상관 없이 한 가지 효과음 설정
