### ISSUE TITLE
[User] ApplicationService 사용자 보상 처리 구현

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/WebRPG#21]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [x] Application
- [x] Domain
---
## 주요 서비스 로직
위 Service 종류 중 Application 일 경우 주요 서비스 로직을 작성해주세요.  

1. 사냥 후 보상 처리 메소드

## 주요 비즈니스 로직
위 Service 종류 중 Domain 일 경우 주요 서비스 로직을 작성해주세요.

1. 사용자 총 보유금 계산
2. 사용자 레벨 업 여부 계산
3. 사용자 경험치 잔량 계산

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   

---

## TODO
- [x]  사냥 후 보상 처리 메소드 구현
- [x] 사용자 총 보유금 계산
- [x] 사용자 레벨 업 여부 계산
- [x] 사용자 경험치 잔량 계산

---

## ETC

---
* 없음
