### ISSUE TITLE
[User] 사용자 레벨업 구현

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/WebRPG#24]
## Description
특정 클래스의 메서드를 수정할 경우 작성하는 이슈 템플릿입니다.

### 아래 항목 중 해당하는 메서드를 수정을 선택해주세요.
- [x] Update
---

## 주요 메서드 로직
새로 업데이트되는 메서드 로직을 작성해주세요.  

1. 레벨 업 필요 경험치 계산
2. 사용자의 현재 보유 경험치 계산(보상 경험치 + 이전 보유 경험치)
3. 사용자의 현재 레벨의 레벨업 필요 경험치와 현재 보유 경험치 비교
    1. 보유 경험치가 레벨업 경험치보다 클 경우 레벨 +1 and 남은 값 보유 경험치로 이전
    2. 보유 경험치가 레벨업 경험치보다 작을 경우 pass

---

## 메서드
해당 클래스의 주요 메서드를 입력합니다.   

---

## TODO
- [x]  레벨 업 필요 경험치 계산 메소드 구현
- [x]  사용자의 현재 보유 경험치 계산 메소드 구현
- [x]  사용자의 현재 레벨의 레벨업 필요 경험치와 현재 보유 경험치 비교 메소드 구현

---

## ETC

---
* 없음
