### ISSUE TITLE
[Monster] (Infra) Service

### ISSUE THREAD

**Issue by ahnichan** [MetaAir2023/WebRPG#4]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [x] Application
- [x] Domain
---
## 주요 서비스 로직
위 Service 종류 중 Application 일 경우 주요 서비스 로직을 작성해주세요.  
(추후 업데이트 예정)
## 주요 비즈니스 로직
위 Service 종류 중 Domain 일 경우 주요 서비스 로직을 작성해주세요.

예시)

1. 아이템 강화 로직
2. 현재 강화 상태 체크 로직

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.   
예시)
- ``calculateUpgradeItem``    
(item `upgradeLevel` 를 매개변수로 받아 강화 성공 여부를 조회하는 메서드)
~~~
private / pulbic : pulbic
parameter : int upgradeLevel
return : upgradeLevel + 1 OR 0 
~~~

---

## TODO
- [x]  할일 목록을 작성한다.
- [x]  할일 목록을 작성한다.
- [x]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
