### ISSUE TITLE
[Upgrade] Application Service 구현

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/WebRPG#43]
## Description
Service 를 개발하였을 경우 사용하는 이슈 템플릿입니다.   
### 아래 항목 중 해당하는 Service의 패키지를 선택해주세요.
- [x] Application
---
## 주요 서비스 로직
위 Service 종류 중 Application 일 경우 주요 서비스 로직을 작성해주세요.  

1. 아이템 강화 메소드 구현
2. 강화 가능 보유금 소지 여부 체크 메소드 구현
3. 강화 후 강화 레벨 저장 메소드 구현

---

---

## TODO
- [x]  아이템 강화 메소드 구현
- [x]  강화 가능 보유금 소지 여부 체크 메소드 구현
- [x]  강화 후 강화 레벨 저장 메소드 구현

---

## ETC

---
* 없음
