### ISSUE TITLE
[Hunt] 몬스터 공격 패턴 및 회복 패턴 구현

### ISSUE THREAD

**Issue by madirony** [MetaAir2023/WebRPG#53]
## Description
- [x] Application
---
## 주요 서비스 로직
1. 몬스터의 체력이 30% 이하일 경우, 회복 패턴을 한번의 전투에서 단 한번만 발동함.
2. 몬스터가 3번 공격할 때마다, 그 다음 공격은 무조건 2번 공격하도록 함.

---

## 주요 메서드
- ``initMonsterPatternDTO``    
(`monsterPatternDTO` 를 초기화하는 메서드)
~~~
private / public : public
parameter : x
return : monsterPatternDTO
~~~
- ``initIntegrateMonsterAttackDTO``    
(`IntegrateMonsterAttackDTO` 를 초기화 생성하는 메서드)
~~~
private / public : public
parameter : MonsterAttackDTO monsterAttackDTO, MonsterPatternDTO monsterPatternDTO
return : integrateMonsterAttackDTO
~~~
- ``attackPattern``    
(`IntegrateMonsterAttackDTO` 를 활용하여 몬스터가 행동하는 패턴들을 구현한 메서드)
~~~
private / public : public
parameter : IntegrateMonsterAttackDTO integrateMonsterAttackDTO
return : integrateMonsterAttackDTO
~~~
---

## TODO
- [x]  몬스터 패턴 DTO를 따로 만들고, 기존 몬스터 공격 DTO와 통합하는 IntegrateMonsterAttackDTO를 생성
- [x]  몬스터 공격 패턴 , 회복 패턴 메소드를 구현
- [x] 새롭게 작성한 메소드 관련 Test Code 작성
---
