### ISSUE TITLE
[Hunt] UserAttack 관련 된 테스트 작성

### ISSUE THREAD

**Issue by pyunghun** [MetaAir2023/WebRPG#57]
## Description
테스트에 관한 이슈 템플릿입니다.

* UserAttackApplicationService 관련 테스트 

---

## 주요 테스트 내용
클래스에서 테스트할 주요 내용을 입력합니다.
예시)
- ``testCheckUpgrade``    
  (domain의 upgradeService의 checkUpgrade 메서드 테스트)
~~~
테스트 메서드 : findUserBySequence()
input : int sequence
assert : "소드마스터", userInfoDTO.getName()
~~~

---

## TODO
- [x]  sequence로 미리 저장되어 있는 유저의 이름을 조회한다.
- [ ]  할일 목록을 작성한다.
- [ ]  할일 목록을 작성한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
