### ISSUE TITLE
[UserAttack] 유저 공격에 따른 테스트 메소드 작성

### ISSUE THREAD

**Issue by pyunghun** [MetaAir2023/WebRPG#67]
## Description
테스트에 관한 이슈 템플릿입니다.

예시)
### 테스트할 클래스 : upgradeService
* UserAttackApplicationService

---

## 주요 테스트 내용
클래스에서 테스트할 주요 내용을 입력합니다.
예시)
- 유저가 몬스터를 공격하였을 시 들어가는 데미지
- 유저의 공격패턴을 검증하는 메소드
- 유저의 30% 미만의 체력일 때 유저의 체력이 회복되는 지 검증
~~~
테스트 메서드 :  추가 예정
input : 
assert : 
~~~

---

## TODO
- [x]  유저의 공격 시 들어가는 데미지 계산하는 검증 로직
- [x]  유저의 공격 시 공격 패턴의 변화 검증 로직
- [x]  유저의 피가 줄어들게 되었을 시 회복하는 검증 로직 

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.
