### ISSUE TITLE
[User] entitiy 생성

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/WebRPG#7]
##Description
Entity 를 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## 필드 정의
해당 엔티티의 필드를 모두 정의합니다.  

| 정의  | 타입  |이름 |
|-----|-----|--------|
| 시퀀스 | int | sequence |
| 이름 | String | name |
| 기본 체력 | int | defaultHP |
| 기본 공격력 | int | defaultSTR |
| 보유한 돈 | Money | money |
| 강화 레벨 | int | upgradeLevel |
| 강화 레벨 | [Enum] Property |  property |
---

## 주요 사용할 클래스
해당 엔티티를 주로 사용할 클래스를 입력합니다.   
예
 - ``class UserInmemoryDatabase``
 - ``interface UserRepository``
 - ``class InmemoryUserRepository``

---

## TODO

---
- [ ] 유저 엔티티 생성
- [ ] Money VO 생성
- [ ] Property Enum 클래스 생성

---

## ETC
* 없음
