### ISSUE TITLE
[User] InmemoryUserRepository 개발

### ISSUE THREAD

**Issue by jiwon11** [MetaAir2023/WebRPG#8]
## Description
Repository 를 개발하였을 경우 사용하는 이슈 템플릿입니다.

---

## 주요 메서드
해당 클래스의 주요 메서드를 입력합니다.

- ``searchUserBySequence`` (user`sequence` 를 매개변수로 받아 사용자 1명을 조회하는 메서드)
- ``getDefaultHP`` (user`sequence` 를 매개변수로 받아 해당 사용자의 기본 체력을 반환하는 메서드)
- ``setDefaultHP`` (user`sequence`, `upgradeLevel` 를 매개변수로 받아 해당 사용자의 기본 체력을 변경하는 메서드)
- ``getDefaultSTR`` (user`sequence` 를 매개변수로 받아 해당 사용자의 기본 공격력을 반환하는 메서드)
- ``setDefaultSTR`` (user`sequence`, `str` 를 매개변수로 받아 해당 사용자의 기본 공격력을 변경하는 메서드)
- ``getMoney`` (user`sequence` 를 매개변수로 받아 해당 사용자의 돈을 반환하는 메서드)
- ``setMoney`` (user`sequence`, `money` 를 매개변수로 받아 해당 사용자의 돈을 변경하는 메서드)
- ``getUpgradeLevel`` (user`sequence` 를 매개변수로 받아 해당 사용자의 강화 레벨을 반환하는 메서드)
- ``setUpgradeLevel`` (user`sequence`, `upgradeLevel` 를 매개변수로 받아 해당 사용자의 강화 레벨을 변경하는 메서드)
- ``getProperty`` (user`sequence` 를 매개변수로 받아 해당 사용자의 속성을 반환하는 메서드)
- ``setProperty`` (user`sequence`, `property` 를 매개변수로 받아 해당 사용자의 강하 레벨을 변경하는 메서드)

---

## TODO
- [x]  UserRepository 상속
- [x]  searchUserBySequence 구현
- [x]  DefaultHP 관련 메소드구현
- [x] DefaultSTR 관련 메소드구현
- [x] Money 관련 메소드구현
- [x] UpgradeLevel 관련 메소드구현
- [x] Property 관련 메소드구현

---

## ETC

---
* 없음
